services:
  app:
    container_name: api_node
    build:
      context: . 
      dockerfile: DockerFile 
    ports:
      - "80:80" 
    depends_on:
      - database_node 
    networks:
      - node_rede 
    env_file:
      - .env 

  database_node:
    container_name: database_node
    image: mariadb:latest
    env_file: 
      - .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - node_volume:/var/lib/mysql
    networks:
      - node_rede

  phpmyadmin:
    container_name: pdmin
    image: phpmyadmin
    environment:
      PMA_HOST: database_node
    ports:
      - "3307:80"
    networks:
      - node_rede

volumes:
  node_volume:
    name: node_volume

networks:
  node_rede:
    name: node_rede
